[package]
name = "libcdio-sys"
version = "3.0.0+2.4.0p2.0.2"
edition = "2024"
authors = ["Joaquim Monteiro <joaquim.monteiro@protonmail.com>"]
description = "Native bindings to the libcdio (and libcdio-paranoia) library"
repository = "https://github.com/MonterraByte/libcdio-sys"
readme = "README.md"
exclude = [
  "/.github",
  "vendor/libcdio/*",
  "!vendor/libcdio/.vs/unistd.h",
  "!vendor/libcdio/COPYING",
  "!vendor/libcdio/include/**/*.h",
  "!vendor/libcdio/lib/**/*.[ch]",
]
keywords = ["ffi", "cd", "cdio", "iso9660", "udf"]
categories = ["external-ffi-bindings", "hardware-support", "multimedia", "multimedia::audio"]
license = "GPL-3.0+"
links = "cdio"

[build-dependencies]
bindgen = "0.72"
cc = { version = "1.4.0" }
system-deps = "7"

[features]
default = ["iso9660", "udf"]
iso9660 = []
udf = []
cdda = []
paranoia = ["cdda"]
vendored = []

# Do not forget vendor/*version.h
[package.metadata.system-deps]
libcdio = ">= 2.4.0, < 3.0.0"
libiso9660 = { version = ">= 2.4.0, < 3.0.0", feature = "iso9660" }
libudf = { version = ">= 2.4.0, < 3.0.0", feature = "udf" }
libcdio_cdda = { version = ">= 10.2+2.0.2, < 10.2+3.0.0", feature = "cdda" }
libcdio_paranoia = { version = ">= 10.2+2.0.2, < 10.2+3.0.0", feature = "paranoia" }

[package.metadata.docs.rs]
all-features = true
