name: Rust CI

on:
  pull_request:
  push:
      branches:
        - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libcdio
        run: |
          sudo apt-get update
          sudo apt-get install -y libcdio-dev libiso9660-dev libudf-dev libcdio-cdda-dev libcdio-paranoia-dev
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --workspace --all-targets --all-features

  semver-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libcdio
        run: |
          sudo apt-get update
          sudo apt-get install -y libcdio-dev libiso9660-dev libudf-dev libcdio-cdda-dev libcdio-paranoia-dev
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
